/** 住宅 / 移动代理配置弹窗的国家池 — 对齐原站 GET /api/my/traffic/{id}/countries。
 *  219 国全量，转录自原站登录态界面（2026-07-16）；名称为英文（原站 zh 界面亦显示英文名）。
 *  count 为节点数：前 6 名为原站截图可见的真实值，其余为锚定后合成的递减演示值
 *  （原站为实时数，本克隆无后端）。XK=科索沃，原站亦无国旗只显 "xk"。 */

export interface TrafficCountry {
  code: string;
  name: string;
  /** 该国可用节点数，0 表示不展示 */
  count: number;
}

export const TRAFFIC_COUNTRIES: TrafficCountry[] = [
  { code: "VN", name: "Vietnam", count: 167964 },
  { code: "US", name: "United States", count: 96243 },
  { code: "BR", name: "Brazil", count: 44165 },
  { code: "GB", name: "United Kingdom", count: 37681 },
  { code: "IN", name: "India", count: 31058 },
  { code: "CA", name: "Canada", count: 29655 },
  { code: "SG", name: "Singapore", count: 28734 },
  { code: "ES", name: "Spain", count: 23783 },
  { code: "FR", name: "France", count: 22404 },
  { code: "TR", name: "Turkey", count: 22054 },
  { code: "IT", name: "Italy", count: 21689 },
  { code: "BD", name: "Bangladesh", count: 20119 },
  { code: "PH", name: "Philippines", count: 20118 },
  { code: "ID", name: "Indonesia", count: 19199 },
  { code: "PK", name: "Pakistan", count: 19198 },
  { code: "CL", name: "Chile", count: 17731 },
  { code: "UA", name: "Ukraine", count: 17730 },
  { code: "IQ", name: "Iraq", count: 16069 },
  { code: "MX", name: "Mexico", count: 16068 },
  { code: "CO", name: "Colombia", count: 15594 },
  { code: "AR", name: "Argentina", count: 14747 },
  { code: "DE", name: "Germany", count: 14746 },
  { code: "EC", name: "Ecuador", count: 13939 },
  { code: "PT", name: "Portugal", count: 13938 },
  { code: "SA", name: "Saudi Arabia", count: 12783 },
  { code: "TH", name: "Thailand", count: 12689 },
  { code: "ZA", name: "South Africa", count: 11813 },
  { code: "AE", name: "United Arab Emirates", count: 11812 },
  { code: "UZ", name: "Uzbekistan", count: 11321 },
  { code: "AU", name: "Australia", count: 11176 },
  { code: "MY", name: "Malaysia", count: 10113 },
  { code: "VE", name: "Venezuela", count: 9812 },
  { code: "SE", name: "Sweden", count: 9290 },
  { code: "IE", name: "Ireland", count: 9289 },
  { code: "IL", name: "Israel", count: 9288 },
  { code: "AZ", name: "Azerbaijan", count: 9006 },
  { code: "OM", name: "Oman", count: 8505 },
  { code: "NL", name: "Netherlands", count: 7741 },
  { code: "MA", name: "Morocco", count: 7740 },
  { code: "PL", name: "Poland", count: 7347 },
  { code: "KE", name: "Kenya", count: 7346 },
  { code: "TN", name: "Tunisia", count: 7345 },
  { code: "NP", name: "Nepal", count: 6536 },
  { code: "DZ", name: "Algeria", count: 6535 },
  { code: "KZ", name: "Kazakhstan", count: 6534 },
  { code: "PE", name: "Peru", count: 5788 },
  { code: "JP", name: "Japan", count: 5787 },
  { code: "KR", name: "South Korea", count: 5786 },
  { code: "AL", name: "Albania", count: 5535 },
  { code: "EG", name: "Egypt", count: 5534 },
  { code: "ET", name: "Ethiopia", count: 4918 },
  { code: "RO", name: "Romania", count: 4917 },
  { code: "HK", name: "Hong Kong", count: 4916 },
  { code: "BE", name: "Belgium", count: 4654 },
  { code: "JO", name: "Jordan", count: 4645 },
  { code: "BG", name: "Bulgaria", count: 3998 },
  { code: "BO", name: "Bolivia", count: 3997 },
  { code: "KH", name: "Cambodia", count: 3942 },
  { code: "PY", name: "Paraguay", count: 3917 },
  { code: "JM", name: "Jamaica", count: 3663 },
  { code: "PS", name: "Palestine", count: 3662 },
  { code: "DO", name: "Dominican Republic", count: 3204 },
  { code: "TT", name: "Trinidad and Tobago", count: 3203 },
  { code: "GE", name: "Georgia", count: 3202 },
  { code: "TW", name: "Taiwan", count: 3061 },
  { code: "RU", name: "Russia", count: 2968 },
  { code: "UY", name: "Uruguay", count: 2716 },
  { code: "CR", name: "Costa Rica", count: 2715 },
  { code: "RS", name: "Serbia", count: 2714 },
  { code: "PR", name: "Puerto Rico", count: 2426 },
  { code: "CH", name: "Switzerland", count: 2357 },
  { code: "KG", name: "Kyrgyzstan", count: 2228 },
  { code: "CI", name: "Côte d'Ivoire", count: 2227 },
  { code: "GR", name: "Greece", count: 2226 },
  { code: "AT", name: "Austria", count: 2134 },
  { code: "KW", name: "Kuwait", count: 2133 },
  { code: "BY", name: "Belarus", count: 1956 },
  { code: "MM", name: "Myanmar", count: 1905 },
  { code: "CZ", name: "Czechia", count: 1746 },
  { code: "HR", name: "Croatia", count: 1745 },
  { code: "LV", name: "Latvia", count: 1664 },
  { code: "LB", name: "Lebanon", count: 1601 },
  { code: "BB", name: "Barbados", count: 1548 },
  { code: "PA", name: "Panama", count: 1471 },
  { code: "SK", name: "Slovakia", count: 1441 },
  { code: "SN", name: "Senegal", count: 1440 },
  { code: "BA", name: "Bosnia and Herzegovina", count: 1310 },
  { code: "MD", name: "Moldova", count: 1309 },
  { code: "AM", name: "Armenia", count: 1308 },
  { code: "QA", name: "Qatar", count: 1172 },
  { code: "HU", name: "Hungary", count: 1171 },
  { code: "NZ", name: "New Zealand", count: 1127 },
  { code: "XK", name: "xk", count: 1126 },
  { code: "BH", name: "Bahrain", count: 1106 },
  { code: "LT", name: "Lithuania", count: 1094 },
  { code: "MT", name: "Malta", count: 1054 },
  { code: "SV", name: "El Salvador", count: 964 },
  { code: "MK", name: "North Macedonia", count: 903 },
  { code: "AO", name: "Angola", count: 902 },
  { code: "TG", name: "Togo", count: 901 },
  { code: "GA", name: "Gabon", count: 786 },
  { code: "MN", name: "Mongolia", count: 770 },
  { code: "CG", name: "Republic of Congo", count: 769 },
  { code: "CY", name: "Cyprus", count: 767 },
  { code: "NO", name: "Norway", count: 685 },
  { code: "BF", name: "Burkina Faso", count: 684 },
  { code: "CN", name: "China", count: 656 },
  { code: "NG", name: "Nigeria", count: 601 },
  { code: "SY", name: "Syria", count: 600 },
  { code: "DK", name: "Denmark", count: 583 },
  { code: "HN", name: "Honduras", count: 582 },
  { code: "UG", name: "Uganda", count: 580 },
  { code: "LY", name: "Libya", count: 554 },
  { code: "EE", name: "Estonia", count: 543 },
  { code: "SI", name: "Slovenia", count: 503 },
  { code: "GT", name: "Guatemala", count: 463 },
  { code: "GH", name: "Ghana", count: 447 },
  { code: "LU", name: "Luxembourg", count: 443 },
  { code: "FI", name: "Finland", count: 442 },
  { code: "ME", name: "Montenegro", count: 422 },
  { code: "TZ", name: "Tanzania", count: 388 },
  { code: "LK", name: "Sri Lanka", count: 377 },
  { code: "BS", name: "Bahamas", count: 348 },
  { code: "SR", name: "Suriname", count: 338 },
  { code: "CW", name: "Curacao", count: 337 },
  { code: "GY", name: "Guyana", count: 313 },
  { code: "TJ", name: "Tajikistan", count: 312 },
  { code: "MZ", name: "Mozambique", count: 311 },
  { code: "MG", name: "Madagascar", count: 307 },
  { code: "GP", name: "Guadeloupe", count: 273 },
  { code: "MO", name: "Macao", count: 272 },
  { code: "AG", name: "Antigua and Barbuda", count: 271 },
  { code: "NI", name: "Nicaragua", count: 250 },
  { code: "LA", name: "Lao People's Democratic Republic", count: 235 },
  { code: "LC", name: "Saint Lucia", count: 234 },
  { code: "MU", name: "Mauritius", count: 226 },
  { code: "BN", name: "Brunei", count: 225 },
  { code: "ZM", name: "Zambia", count: 224 },
  { code: "CD", name: "DR Congo", count: 199 },
  { code: "CM", name: "Cameroon", count: 187 },
  { code: "ZW", name: "Zimbabwe", count: 186 },
  { code: "BJ", name: "Benin", count: 185 },
  { code: "MV", name: "Maldives", count: 184 },
  { code: "RE", name: "Réunion", count: 168 },
  { code: "BM", name: "Bermuda", count: 167 },
  { code: "SO", name: "Somalia", count: 157 },
  { code: "MQ", name: "Martinique", count: 148 },
  { code: "CV", name: "Cabo Verde", count: 145 },
  { code: "ML", name: "Mali", count: 137 },
  { code: "BZ", name: "Belize", count: 134 },
  { code: "BW", name: "Botswana", count: 133 },
  { code: "NA", name: "Namibia", count: 130 },
  { code: "GD", name: "Grenada", count: 125 },
  { code: "VG", name: "British Virgin Islands", count: 114 },
  { code: "IS", name: "Iceland", count: 108 },
  { code: "VC", name: "Saint Vincent and the Grenadines", count: 104 },
  { code: "SX", name: "Sint Maarten", count: 103 },
  { code: "AD", name: "Andorra", count: 102 },
  { code: "VI", name: "U.S. Virgin Islands", count: 101 },
  { code: "KY", name: "Cayman Islands", count: 100 },
  { code: "BT", name: "Bhutan", count: 95 },
  { code: "FJ", name: "Fiji", count: 84 },
  { code: "MR", name: "Mauritania", count: 81 },
  { code: "JE", name: "Jersey", count: 79 },
  { code: "DM", name: "Dominica", count: 75 },
  { code: "SC", name: "Seychelles", count: 74 },
  { code: "AF", name: "Afghanistan", count: 72 },
  { code: "KN", name: "Saint Kitts and Nevis", count: 71 },
  { code: "NC", name: "New Caledonia", count: 70 },
  { code: "RW", name: "Rwanda", count: 69 },
  { code: "AW", name: "Aruba", count: 62 },
  { code: "GG", name: "Guernsey", count: 58 },
  { code: "GF", name: "French Guiana", count: 57 },
  { code: "GM", name: "Gambia", count: 56 },
  { code: "YE", name: "Yemen", count: 55 },
  { code: "GU", name: "Guam", count: 52 },
  { code: "BQ", name: "Caribbean Netherlands", count: 51 },
  { code: "IM", name: "Isle of Man", count: 47 },
  { code: "MW", name: "Malawi", count: 46 },
  { code: "AI", name: "Anguilla", count: 45 },
  { code: "GI", name: "Gibraltar", count: 44 },
  { code: "HT", name: "Haiti", count: 43 },
  { code: "SL", name: "Sierra Leone", count: 41 },
  { code: "DJ", name: "Djibouti", count: 38 },
  { code: "NE", name: "Niger", count: 37 },
  { code: "ST", name: "Sao Tome and Principe", count: 36 },
  { code: "SZ", name: "Eswatini", count: 35 },
  { code: "TC", name: "Turks and Caicos Islands", count: 34 },
  { code: "GN", name: "Guinea", count: 33 },
  { code: "LR", name: "Liberia", count: 31 },
  { code: "SM", name: "San Marino", count: 30 },
  { code: "LI", name: "Liechtenstein", count: 29 },
  { code: "SD", name: "Sudan", count: 28 },
  { code: "YT", name: "Mayotte", count: 27 },
  { code: "LS", name: "Lesotho", count: 26 },
  { code: "CU", name: "Cuba", count: 24 },
  { code: "PF", name: "French Polynesia", count: 23 },
  { code: "MC", name: "Monaco", count: 22 },
  { code: "IR", name: "Iran", count: 21 },
  { code: "GW", name: "Guinea-Bissau", count: 20 },
  { code: "GQ", name: "Equatorial Guinea", count: 19 },
  { code: "PW", name: "Palau", count: 18 },
  { code: "BI", name: "Burundi", count: 17 },
  { code: "FK", name: "Falkland Islands", count: 16 },
  { code: "MS", name: "Montserrat", count: 15 },
  { code: "PG", name: "Papua New Guinea", count: 14 },
  { code: "TD", name: "Chad", count: 13 },
  { code: "TM", name: "Turkmenistan", count: 12 },
  { code: "TO", name: "Tonga", count: 11 },
  { code: "FM", name: "Micronesia", count: 10 },
  { code: "TL", name: "Timor-Leste", count: 9 },
  { code: "VU", name: "Vanuatu", count: 8 },
  { code: "FO", name: "Faroe Islands", count: 7 },
  { code: "CK", name: "Cook Islands", count: 6 },
  { code: "GL", name: "Greenland", count: 5 },
  { code: "WS", name: "Samoa", count: 4 },
  { code: "KM", name: "Comoros", count: 3 },
  { code: "ER", name: "Eritrea", count: 3 },
  { code: "SS", name: "South Sudan", count: 3 },
];
