import { docMetadata } from "@/lib/page-meta";
import { syne } from "@/lib/proton-fonts";
import { cn } from "@/lib/utils";
import { Shield, KeyRound, ArrowRight } from "lucide-react";

export const metadata = docMetadata(
  "Enter Token",
  "/sign-in",
  "Access your anonymous VPN session via token.",
);

export default function SignInPage() {
  return (
    <div className="relative flex min-h-[80vh] flex-col items-center justify-center px-4 py-16">
      <div
        aria-hidden
        className="pointer-events-none absolute inset-x-0 top-1/4 -z-10 h-[400px] bg-[radial-gradient(ellipse_50%_50%_at_50%_50%,rgb(16_185_129/_0.07),transparent_75%)]"
      />

      <div className="w-full max-w-md">
        <div className="mb-8 flex justify-center">
          <div className="flex size-16 items-center justify-center rounded-2xl bg-emerald-500/10 text-emerald-400 ring-1 ring-emerald-400/20">
            <Shield className="size-8" strokeWidth={1.5} />
          </div>
        </div>

        <h1
          className={cn(
            syne.className,
            "text-center text-3xl font-semibold tracking-tight text-zinc-50 sm:text-4xl",
          )}
        >
          Anonymous Access
        </h1>
        <p className="mt-4 text-center text-[15px] leading-relaxed text-zinc-400">
          No email, no password. Just enter the unique token generated by your
          VPN app to manage your subscription.
        </p>

        <form className="mt-10 rounded-3xl border border-white/[0.08] bg-white/[0.02] p-6 backdrop-blur-md sm:p-8">
          <div className="space-y-6">
            <div>
              <label
                htmlFor="token"
                className="mb-2 block text-sm font-medium text-zinc-200"
              >
                Access Token
              </label>
              <div className="relative">
                <div className="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-4">
                  <KeyRound className="size-5 text-emerald-400/60" />
                </div>
                <input
                  type="text"
                  id="token"
                  name="token"
                  placeholder="XXXX-XXXX-XXXX-XXXX"
                  className="block w-full rounded-xl border border-white/[0.08] bg-white/[0.03] py-3 pl-11 pr-4 text-zinc-50 placeholder:text-zinc-600 focus:border-emerald-500/50 focus:bg-white/[0.05] focus:outline-none focus:ring-1 focus:ring-emerald-500/20 sm:text-sm"
                  required
                />
              </div>
              <p className="mt-2 text-xs text-zinc-500">
                You can find your token in the app settings after installation.
              </p>
            </div>

            <button
              type="button"
              className="group flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-500 px-4 py-3 text-sm font-semibold text-[oklch(0.08_0_0)] shadow-[0_4px_20px_rgb(16_185_129/_0.35)] transition-all hover:bg-emerald-400 hover:shadow-[0_6px_28px_rgb(16_185_129/_0.5)] focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:ring-offset-2 focus:ring-offset-zinc-950"
            >
              Authenticate
              <ArrowRight className="size-4 transition-transform group-hover:translate-x-1" />
            </button>
          </div>
        </form>

        <div className="mt-8 text-center text-sm text-zinc-500">
          Don&apos;t have a token yet?{" "}
          <a
            href="/download"
            className="font-medium text-emerald-400 hover:text-emerald-300"
          >
            Download the app
          </a>{" "}
          first.
        </div>
      </div>
    </div>
  );
}
